<?
$text = str_replace(':adolf:','<img src=i/smile/adolf.gif>',$text);
$text = str_replace(':am:','<img src=i/smile/am.gif>',$text);
$text = str_replace(':angel:','<img src=i/smile/angel.gif>',$text);
$text = str_replace(':angl:','<img src=i/smile/angl.gif>',$text);
$text = str_replace(':aplause:','<img src=i/smile/aplause.gif>',$text);
$text = str_replace(':arrow:','<img src=i/smile/arrow.gif>',$text);
$text = str_replace(':baby:','<img src=i/smile/baby.gif>',$text);
$text = str_replace(':batman:','<img src=i/smile/batman.gif>',$text);
$text = str_replace(':beer:','<img src=i/smile/beer.gif>',$text);
$text = str_replace(':boxing:','<img src=i/smile/boxing.gif>',$text);
$text = str_replace(':bye:','<img src=i/smile/bye.gif>',$text);
$text = str_replace(':censored:','<img src=i/smile/censored.gif>',$text);
$text = str_replace(':cola:','<img src=i/smile/cola.gif>',$text);
$text = str_replace(':compkill:','<img src=i/smile/compkill.gif>',$text);
$text = str_replace(':cool:','<img src=i/smile/cool.gif>',$text);
$text = str_replace(':coolman:','<img src=i/smile/coolman.gif>',$text);
$text = str_replace(':crazy:','<img src=i/smile/crazy.gif>',$text);
$text = str_replace(':devil:','<img src=i/smile/devil.gif>',$text);
$text = str_replace(':dinner:','<img src=i/smile/dinner.gif>',$text);
$text = str_replace(':dollar:','<img src=i/smile/dollar.gif>',$text);
$text = str_replace(':drink:','<img src=i/smile/drink.gif>',$text);
$text = str_replace(':droch:','<img src=i/smile/droch.gif>',$text);
$text = str_replace(':duel:','<img src=i/smile/duel.gif>',$text);
$text = str_replace(':evil:','<img src=i/smile/evil.gif>',$text);
$text = str_replace(':face1:','<img src=i/smile/face1.gif>',$text);
$text = str_replace(':face2:','<img src=i/smile/face2.gif>',$text);
$text = str_replace(':face3:','<img src=i/smile/face3.gif>',$text);
$text = str_replace(':face4:','<img src=i/smile/face4.gif>',$text);
$text = str_replace(':face5:','<img src=i/smile/face5.gif>',$text);
$text = str_replace(':fingal:','<img src=i/smile/fingal.gif>',$text);
$text = str_replace(':friday:','<img src=i/smile/friday.gif>',$text);
$text = str_replace(':fuck:','<img src=i/smile/fuck.gif>',$text);
$text = str_replace(':fuu:','<img src=i/smile/fuu.gif>',$text);
$text = str_replace(':girl:','<img src=i/smile/girl.gif>',$text);
$text = str_replace(':goodnigth:','<img src=i/smile/goodnigth.gif>',$text);
$text = str_replace(':gun1:','<img src=i/smile/gun1.gif>',$text);
$text = str_replace(':gun2:','<img src=i/smile/gun2.gif>',$text);
$text = str_replace(':gun_1:','<img src=i/smile/gun_1.gif>',$text);
$text = str_replace(':ha:','<img src=i/smile/ha.gif>',$text);
$text = str_replace(':happy:','<img src=i/smile/happy.gif>',$text);
$text = str_replace(':heart:','<img src=i/smile/heart.gif>',$text);
$text = str_replace(':hello:','<img src=i/smile/hello.gif>',$text);
$text = str_replace(':helloween:','<img src=i/smile/helloween.gif>',$text);
$text = str_replace(':help:','<img src=i/smile/help.gif>',$text);
$text = str_replace(':hummer:','<img src=i/smile/hummer.gif>',$text);
$text = str_replace(':hummer2:','<img src=i/smile/hummer2.gif>',$text);
$text = str_replace(':ill:','<img src=i/smile/ill.gif>',$text);
$text = str_replace(':inlove:','<img src=i/smile/inlove.gif>',$text);
$text = str_replace(':invalid:','<img src=i/smile/invalid.gif>',$text);
$text = str_replace(':jack:','<img src=i/smile/jack.gif>',$text);
$text = str_replace(':jedy:','<img src=i/smile/jedy.gif>',$text);
$text = str_replace(':kill:','<img src=i/smile/kill.gif>',$text);
$text = str_replace(':killed:','<img src=i/smile/killed.gif>',$text);
$text = str_replace(':king:','<img src=i/smile/king.gif>',$text);
$text = str_replace(':kiss:','<img src=i/smile/kiss.gif>',$text);
$text = str_replace(':kiss1:','<img src=i/smile/kiss1.gif>',$text);
$text = str_replace(':kiss2:','<img src=i/smile/kiss2.gif>',$text);
$text = str_replace(':kiss3:','<img src=i/smile/kiss3.gif>',$text);
$text = str_replace(':kiss4:','<img src=i/smile/kiss4.gif>',$text);
$text = str_replace(':kiss5:','<img src=i/smile/kiss5.gif>',$text);
$text = str_replace(':knut:','<img src=i/smile/knut.gif>',$text);
$text = str_replace(':lick:','<img src=i/smile/lick.gif>',$text);
$text = str_replace(':lips:','<img src=i/smile/lips.gif>',$text);
$text = str_replace(':lock:','<img src=i/smile/lock.gif>',$text);
$text = str_replace(':lol:','<img src=i/smile/lol.gif>',$text);
$text = str_replace(':loo:','<img src=i/smile/loo.gif>',$text);
$text = str_replace(':luck:','<img src=i/smile/luck.gif>',$text);
$text = str_replace(':mac:','<img src=i/smile/mac.gif>',$text);
$text = str_replace(':man_hat:','<img src=i/smile/man_hat.gif>',$text);
$text = str_replace(':matrix:','<img src=i/smile/matrix.gif>',$text);
$text = str_replace(':med:','<img src=i/smile/med.gif>',$text);
$text = str_replace(':mediana:','<img src=i/smile/mediana.gif>',$text);
$text = str_replace(':merlin:','<img src=i/smile/merlin.gif>',$text);
$text = str_replace(':minet:','<img src=i/smile/minet.gif>',$text);
$text = str_replace(':mol:','<img src=i/smile/mol.gif>',$text);
$text = str_replace(':music:','<img src=i/smile/music.gif>',$text);
$text = str_replace(':newyear:','<img src=i/smile/newyear.gif>',$text);
$text = str_replace(':ninja:','<img src=i/smile/ninja.gif>',$text);
$text = str_replace(':nuclear:','<img src=i/smile/nuclear.gif>',$text);
$text = str_replace(':nunchak:','<img src=i/smile/nunchak.gif>',$text);
$text = str_replace(':ogo:','<img src=i/smile/ogo.gif>',$text);
$text = str_replace(':pare:','<img src=i/smile/pare.gif>',$text);
$text = str_replace(':police:','<img src=i/smile/police.gif>',$text);
$text = str_replace(':police2:','<img src=i/smile/police2.gif>',$text);
$text = str_replace(':prise:','<img src=i/smile/prise.gif>',$text);
$text = str_replace(':punk:','<img src=i/smile/punk.gif>',$text);
$text = str_replace(':question:','<img src=i/smile/question.gif>',$text);
$text = str_replace(':ravvin:','<img src=i/smile/ravvin.gif>',$text);
$text = str_replace(':ravvin2:','<img src=i/smile/ravvin2.gif>',$text);
$text = str_replace(':rip:','<img src=i/smile/rip.gif>',$text);
$text = str_replace(':rupor:','<img src=i/smile/rupor.gif>',$text);
$text = str_replace(':scare:','<img src=i/smile/scare.gif>',$text);
$text = str_replace(':shut:','<img src=i/smile/shut.gif>',$text);
$text = str_replace(':sleep:','<img src=i/smile/sleep.gif>',$text);
$text = str_replace(':song:','<img src=i/smile/song.gif>',$text);
$text = str_replace(':sperm:','<img src=i/smile/sperm.gif>',$text);
$text = str_replace(':strong:','<img src=i/smile/strong.gif>',$text);
$text = str_replace(':student:','<img src=i/smile/student.gif>',$text);
$text = str_replace(':t2:','<img src=i/smile/t2.gif>',$text);
$text = str_replace(':terminator:','<img src=i/smile/terminator.gif>',$text);
$text = str_replace(':throwout:','<img src=i/smile/throwout.gif>',$text);
$text = str_replace(':training:','<img src=i/smile/training.gif>',$text);
$text = str_replace(':trax4:','<img src=i/smile/trax4.gif>',$text);
$text = str_replace(':trio:','<img src=i/smile/trio.gif>',$text);
$text = str_replace(':two:','<img src=i/smile/two.gif>',$text);
$text = str_replace(':user:','<img src=i/smile/user.gif>',$text);
$text = str_replace(':wow:','<img src=i/smile/wow.gif>',$text);
$text = str_replace(':yo:','<img src=i/smile/yo.gif>',$text);



// РВС
$text = str_replace('e p o h a','???',$text);
$text = str_replace('epoha','???',$text);
$text = str_replace('EPOHA','???',$text);
$text = str_replace('e p o h a . u s','???',$text);
$text = str_replace('epoha.us','*',$text);
$text = str_replace('?g o _ s p=','???',$text);
$text = str_replace('?go_sp=','???',$text);
$text = str_replace('?rc=','???',$text);
$text = str_replace('?r=','???',$text);
$text = str_replace('?uc=','???',$text);
$text = str_replace('travian','langels',$text);
$text = str_replace('instincts','langels',$text);
$text = str_replace('instinct','langels',$text);
$text = str_replace('devilwar','langels',$text);
$text = str_replace('d e v i l w a r','langels',$text);
$text = str_replace('lastworlds','langels',$text);
$text = str_replace('D E V I L W A R','langels',$text);
$text = str_replace('hosting99','langels',$text);
$text = str_replace('last.nezhin','langels',$text);
$text = str_replace('kolize','langels',$text);
$text = str_replace('combats','langels',$text);
$text = str_replace('haddan','langels',$text);
$text = str_replace('lads.lathost','langels',$text);
$text = str_replace('emphwar','langels',$text);
$text = str_replace('newrpg','langels',$text);
$text = str_replace('neverlands','langels',$text);
$text = str_replace('taleworldgame','langels',$text);
$text = str_replace('chaosroad','langels',$text);
$text = str_replace('planetwow','langels',$text);
$text = str_replace('real-game-ru','langels',$text);
$text = str_replace('evolutions','langels',$text);
$text = str_replace('carnage','langels',$text);
$text = str_replace('lovrik.spblink.ru','langels',$text);
$text = str_replace('lostworlds','langels',$text);
$text = str_replace('apeha','langels',$text);
$text = str_replace('twog','langels',$text);
$text = str_replace('tlworld','langels',$text);
$text = str_replace('ereality','langels',$text);
$text = str_replace('dangerwars','langels',$text);
$text = str_replace('newcombats','langels',$text);
$text = str_replace('n e w c o m b a t s','langels',$text);
$text = str_replace('com','ru',$text);
$text = str_replace('instinkts','langels',$text);
$text = str_replace('neverfate','langels',$text);
$text = str_replace('бля','*censored*',$text);
$text = str_replace('сука','*censored*',$text);
$text = str_replace('пизд','*censored*',$text);
$text = str_replace('хуй','*censored*',$text);
$text = str_replace('мля','*censored*',$text);
$text = str_replace('пля','*censored*',$text);
$text = str_replace('Еба','*censored*',$text);
$text = str_replace('йух','*censored*',$text);
$text = str_replace('хуе','*censored*',$text);
$text = str_replace('аеб','*censored*',$text);
$text = str_replace('долбаеб','*censored*',$text);
$text = str_replace('аёб','*censored*',$text);
$text = str_replace('ёб','*censored*',$text);
$text = str_replace('х у й','*censored*',$text);
$text = str_replace('х у и','*censored*',$text);
$text = str_replace('е б а','*censored*',$text);
$text = str_replace('е б у','*censored*',$text);
$text = str_replace('еба','*censored*',$text);
$text = str_replace('пизь','*censored*',$text);
$text = str_replace('залупа','*censored*',$text);
$text = str_replace('шдюха','*censored*',$text);
$text = str_replace('гомик','*censored*',$text);
$text = str_replace('чмо','*censored*',$text);
$text = str_replace('чмы','*censored*',$text);
?>